# Generated by Django 2.0.2 on 2019-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='FIELDNAME',
            field=models.ImageField(default='default.png', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.ImageField(default='标题', max_length=20, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='这是作品的简介', max_length=80),
        ),
    ]
