# Generated by Django 2.0.2 on 2019-08-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190815_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='标题', max_length=20),
        ),
    ]
