# Generated by Django 2.0.2 on 2019-08-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190815_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='FIELDNAME',
            new_name='image',
        ),
    ]
